---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userfrontend-deployment
  labels:
    app: user-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
        - name: user-frontend
          image: jackjackzhou/user-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: user-frontend-servies
spec:
  type: LoadBalancer
  ports:
  - port: 3011
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: user-frontend
